(function(){
  function initHRDemo(){
    const root=document.querySelector('.preview-hr');
    if(!root||root.dataset.hrReady)return;
    root.dataset.hrReady='1';
    const en=document.documentElement.lang==='en';
    const text=en?{
      brand:'HR Reserve',dashboard:'Dashboard',candidates:'Candidates',vacancies:'Vacancies',applications:'Applications',interviews:'Interviews',reviews:'Reviews',skills:'Soft skills',search:'Search…',add:'Add',all:'All',new:'New',screening:'Screening',interview:'Interview',test:'Test task',offer:'Offer',hired:'Hired',rejected:'Rejected',open:'Open',paused:'Paused',closed:'Closed',today:'Today',thisWeek:'This week',view:'View',save:'Save',cancel:'Cancel',back:'Back',edit:'Edit',move:'Move to next stage',message:'Message',schedule:'Schedule interview',newCandidate:'New candidate',newVacancy:'New vacancy',newInterview:'New interview',name:'Name',role:'Role',location:'Location',email:'Email',phone:'Phone',stage:'Stage',score:'Match',experience:'Experience',salary:'Salary',company:'Company',status:'Status',date:'Date',type:'Type',result:'Result',review:'Review',rating:'Rating',comment:'Comment',demo:'Interactive demo · local data',local:'All changes stay in this demo',saved:'Saved in demo',updated:'Updated',close:'Close',empty:'Nothing here yet.',resume:'Resume',overview:'Overview',activity:'Activity',softSkills:'Soft skills',notes:'Notes',applicationsTitle:'Applications',interviewTitle:'Interviews',reviewsTitle:'Interviewer reviews',skillsTitle:'Soft skills overview',candidateAdded:'Candidate added',vacancyAdded:'Vacancy added',interviewAdded:'Interview scheduled',advance:'Moved to next stage',messageCreated:'Message draft created',export:'Export CSV'
    }:{
      brand:'HR Reserve',dashboard:'Дашборд',candidates:'Кандидати',vacancies:'Вакансії',applications:'Заявки',interviews:'Співбесіди',reviews:'Відгуки',skills:'Soft skills',search:'Пошук…',add:'Додати',all:'Усі',new:'Нові',screening:'Перевірка',interview:'Співбесіда',test:'Тестове',offer:'Офер',hired:'Найняті',rejected:'Відхилені',open:'Відкрита',paused:'На паузі',closed:'Закрита',today:'Сьогодні',thisWeek:'Цього тижня',view:'Переглянути',save:'Зберегти',cancel:'Скасувати',back:'Назад',edit:'Редагувати',move:'Перевести далі',message:'Написати',schedule:'Призначити співбесіду',newCandidate:'Новий кандидат',newVacancy:'Нова вакансія',newInterview:'Нова співбесіда',name:"Ім’я",role:'Посада',location:'Місто',email:'Email',phone:'Телефон',stage:'Етап',score:'Відповідність',experience:'Досвід',salary:'Зарплата',company:'Компанія',status:'Статус',date:'Дата',type:'Тип',result:'Результат',review:'Відгук',rating:'Оцінка',comment:'Коментар',demo:'Інтерактивна демоверсія · локальні дані',local:'Усі зміни залишаються в цій демоверсії',saved:'Збережено в демо',updated:'Оновлено',close:'Закрити',empty:'Тут поки нічого немає.',resume:'Резюме',overview:'Огляд',activity:'Активність',softSkills:'Soft skills',notes:'Нотатки',applicationsTitle:'Заявки',interviewTitle:'Співбесіди',reviewsTitle:'Відгуки інтерв’юерів',skillsTitle:'Огляд soft skills',candidateAdded:'Кандидата додано',vacancyAdded:'Вакансію додано',interviewAdded:'Співбесіду призначено',advance:'Кандидата переведено далі',messageCreated:'Чернетку повідомлення створено',export:'Експорт CSV'
    };

    const stages=['New','Screening','Interview','TestTask','Offer','Hired','Rejected'];
    const data={
      candidates:[
        {id:1,name:'Анна Коваль',role:'Frontend Developer',stage:'Interview',score:92,location:'Київ',email:'anna@example.com',phone:'+380 67 000 00 01',experience:'3 роки',salary:'$1,700',skills:[9,9,8,10,9],activity:['Резюме переглянуто','Погоджено співбесіду','Надіслано тестове']},
        {id:2,name:'Максим Шевченко',role:'Backend Developer',stage:'Screening',score:87,location:'Львів',email:'maksym@example.com',phone:'+380 67 000 00 02',experience:'4 роки',salary:'$2,100',skills:[10,8,9,8,9],activity:['Створено заявку','Проведено screening']},
        {id:3,name:'Олена Бондар',role:'UI/UX Designer',stage:'Offer',score:95,location:'Рівне',email:'olena@example.com',phone:'+380 67 000 00 03',experience:'5 років',salary:'$1,900',skills:[10,10,9,10,9],activity:['Фінальне інтерв’ю','Офер підготовлено']},
        {id:4,name:'Ігор Мельник',role:'QA Engineer',stage:'New',score:81,location:'Одеса',email:'ihor@example.com',phone:'+380 67 000 00 04',experience:'2 роки',salary:'$1,300',skills:[8,8,7,9,8],activity:['Резюме завантажено']},
        {id:5,name:'Марія Ткач',role:'Project Manager',stage:'Interview',score:90,location:'Дніпро',email:'maria@example.com',phone:'+380 67 000 00 05',experience:'6 років',salary:'$2,000',skills:[9,10,9,9,10],activity:['Screening пройдено','Співбесіду призначено']},
        {id:6,name:'Данило Руденко',role:'Full-stack Developer',stage:'Hired',score:96,location:'Київ',email:'danylo@example.com',phone:'+380 67 000 00 06',experience:'6 років',salary:'$2,400',skills:[10,9,10,10,9],activity:['Підписано офер','Найнятий']}
      ],
      vacancies:[
        {id:1,title:'Backend Developer',company:'Acme Studio',status:'Open',priority:'High',candidates:7,salary:'$1,900–2,500'},
        {id:2,title:'Frontend Developer',company:'Acme Studio',status:'Open',priority:'Normal',candidates:14,salary:'$1,500–2,100'},
        {id:3,title:'QA Engineer',company:'North Labs',status:'Paused',priority:'Normal',candidates:5,salary:'$1,200–1,700'},
        {id:4,title:'Project Manager',company:'North Labs',status:'Open',priority:'High',candidates:4,salary:'$1,800–2,400'}
      ],
      interviews:[
        {id:1,date:'2026-08-24 11:00',candidateId:1,type:'Video',result:'Planned',owner:'Recruiter'},
        {id:2,date:'2026-08-24 14:30',candidateId:5,type:'Technical',result:'Planned',owner:'Interviewer'},
        {id:3,date:'2026-08-25 10:00',candidateId:4,type:'Screening',result:'Planned',owner:'Recruiter'},
        {id:4,date:'2026-08-25 16:00',candidateId:3,type:'Final',result:'Passed',owner:'Recruiter'}
      ],
      reviews:[
        {candidateId:1,interviewer:'Олег Кравець',rating:9,comment:'Сильний frontend, добре пояснює рішення.'},
        {candidateId:3,interviewer:'Ірина Гнатюк',rating:10,comment:'Дуже сильне портфоліо та системний підхід.'},
        {candidateId:5,interviewer:'Павло Шевчук',rating:9,comment:'Хороша комунікація та досвід.'}
      ]
    };

    const state={page:'dashboard',query:'',filter:'All',selected:null,modal:null};
    root.className='preview preview-hr hr-demo hr-full';
    root.innerHTML=`<div class="hr-app-shell">
      <aside class="hr-sidebar"><div class="hr-logo"><span>HR</span><b>Reserve</b></div><div class="hr-nav-group"><small>WORKSPACE</small><button data-page="dashboard" class="active"><i>⌂</i>${t.dashboard}</button><button data-page="candidates"><i>◎</i>${t.candidates}<b class="hr-nav-count">6</b></button><button data-page="vacancies"><i>▦</i>${t.vacancies}</button><button data-page="applications"><i>◌</i>${t.applications}</button><button data-page="interviews"><i>◷</i>${t.interviews}</button></div><div class="hr-nav-group"><small>PEOPLE</small><button data-page="reviews"><i>★</i>${t.reviews}</button><button data-page="skills"><i>◈</i>${t.skills}</button></div><div class="hr-sidebar-bottom"><span class="hr-demo-pill"><i></i>${en?'DEMO':'ДЕМО'}</span><small>${t.local}</small></div></aside>
      <section class="hr-main"><header class="hr-app-top"><button class="hr-mobile-menu" type="button">☰</button><div><strong data-page-title>${t.dashboard}</strong><small>${t.demo}</small></div><div class="hr-top-actions"><label class="hr-search-main"><span>⌕</span><input data-global-search placeholder="${t.search}"></label><button class="hr-icon-btn" data-top-add type="button">＋</button><div class="hr-user"><span>MB</span><b>Max</b></div></div></header><div class="hr-app-content" data-content></div></section>
    </div><div class="hr-toast" role="status" aria-live="polite"></div><div class="hr-app-modal" aria-hidden="true"><div class="hr-modal-backdrop"></div><div class="hr-modal-card"></div></div>`;

    const content=root.querySelector('[data-content]'),toast=root.querySelector('.hr-toast'),modal=root.querySelector('.hr-app-modal'),modalCard=root.querySelector('.hr-modal-card');
    const navButtons=root.querySelectorAll('[data-page]');
    const stageLabel=s=>({New:t.new,Screening:t.screening,Interview:t.interview,TestTask:t.test,Offer:t.offer,Hired:t.hired,Rejected:t.rejected}[s]||s);
    const statusLabel=s=>({Open:t.open,Paused:t.paused,Closed:t.closed}[s]||s);
    const candidateById=id=>data.candidates.find(c=>c.id===id);
    const candidateName=id=>candidateById(id)?.name||'—';
    function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1700)}
    function setPage(page){state.page=page;state.selected=null;navButtons.forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderPage()}
    function openMiniModal(html,after){modalCard.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');modalCard.querySelectorAll('[data-modal-close]').forEach(b=>b.onclick=closeModal);if(after)after()}
    function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');modalCard.innerHTML=''}
    modal.querySelector('.hr-modal-backdrop').addEventListener('click',closeModal);

    function header(title,sub,actionText){return `<div class="hr-page-head"><div><span class="hr-page-kicker">HR RESERVE / ${title.toUpperCase()}</span><h1>${title}</h1><p>${sub}</p></div>${actionText?`<button class="hr-primary-btn" data-action="${actionText==='addCandidate'?'addCandidate':actionText==='addVacancy'?'addVacancy':'addInterview'}">＋ ${actionText==='addCandidate'?t.newCandidate:actionText==='addVacancy'?t.newVacancy:t.newInterview}</button>`:''}</div>`}
    function renderPage(){
      const titles={dashboard:t.dashboard,candidates:t.candidates,vacancies:t.vacancies,applications:t.applications,interviews:t.interviews,reviews:t.reviews,skills:t.skills};root.querySelector('[data-page-title]').textContent=titles[state.page];
      if(state.page==='dashboard')renderDashboard();
      else if(state.page==='candidates')renderCandidates();
      else if(state.page==='vacancies')renderVacancies();
      else if(state.page==='applications')renderApplications();
      else if(state.page==='interviews')renderInterviews();
      else if(state.page==='reviews')renderReviews();
      else renderSkills();
      bindPageActions();
    }
    function renderDashboard(){
      const open=data.vacancies.filter(v=>v.status==='Open').length;const interviews=data.interviews.filter(i=>i.result==='Planned').length;const hired=data.candidates.filter(c=>c.stage==='Hired').length;
      content.innerHTML=`${header(t.dashboard,en?'A quick view of the recruitment workflow.':'Короткий огляд усього процесу найму.')}<div class="hr-stat-grid"><button data-go="candidates"><small>${t.candidates}</small><b>${data.candidates.length}</b><span>+12% ${t.thisWeek.toLowerCase()}</span><i>→</i></button><button data-go="vacancies"><small>${t.vacancies}</small><b>${open}</b><span>${data.vacancies.length-open} ${t.paused.toLowerCase()}</span><i>→</i></button><button data-go="interviews"><small>${t.interviews}</small><b>${interviews}</b><span>${hired} ${t.hired.toLowerCase()}</span><i>→</i></button><button data-go="applications"><small>${t.applications}</small><b>18</b><span>7 ${t.test.toLowerCase()}</span><i>→</i></button></div><div class="hr-dashboard-grid"><div class="hr-panel hr-funnel"><div class="hr-panel-head"><div><b>${en?'Hiring funnel':'Воронка найму'}</b><small>${en?'Current pipeline':'Поточна воронка'}</small></div></div>${[['New',6],['Screening',2],['Interview',2],['TestTask',1],['Offer',1],['Hired',1]].map(x=>`<button class="hr-funnel-row" data-go="candidates" data-filter="${x[0]}"><span>${stageLabel(x[0])}</span><div><i style="width:${Math.max(18,x[1]*13)}%"></i></div><b>${x[1]}</b></button>`).join('')}</div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Today':'Сьогодні'}</b><small>${en?'Upcoming interviews':'Найближчі співбесіди'}</small></div><button class="hr-link-btn" data-go="interviews">${t.view}</button></div><div class="hr-mini-list">${data.interviews.slice(0,3).map(i=>`<button data-interview="${i.id}"><span>${i.date.split(' ')[1]}</span><b>${candidateName(i.candidateId)}</b><small>${i.type}</small></button>`).join('')}</div></div></div><div class="hr-panel hr-activity"><div class="hr-panel-head"><div><b>${en?'Recent activity':'Остання активність'}</b><small>${en?'Local demo state':'Стан демоверсії'}</small></div></div><div class="hr-activity-list">${['Нова заявка від Анни Коваль','Співбесіду Анни призначено на 11:00','Олена Бондар отримала офер','Данило Руденко переведений у Hired'].map((x,i)=>`<div><span>${i+1}</span><p>${x}<small>${i+2} ${en?'min ago':'хв тому'}</small></p></div>`).join('')}</div></div>`;
    }
    function renderCandidates(){
      const q=state.query.toLowerCase();const list=data.candidates.filter(c=>(state.filter==='All'||c.stage===state.filter)&&(`${c.name} ${c.role} ${c.location}`.toLowerCase().includes(q)));
      content.innerHTML=`${header(t.candidates,en?'Candidates, pipeline stages and details.':'Кандидати, етапи та повна картка кандидата.','addCandidate')}<div class="hr-list-toolbar"><label class="hr-search-inline">⌕<input data-candidate-search value="${state.query}" placeholder="${t.search}"></label><div class="hr-chip-row">${['All',...stages].map(f=>`<button class="${state.filter===f?'active':''}" data-filter="${f}">${f==='All'?t.all:stageLabel(f)}</button>`).join('')}</div><button class="hr-outline-btn" data-export>${t.export}</button></div><div class="hr-table-head"><span>${t.name}</span><span>${t.role}</span><span>${t.stage}</span><span>${t.score}</span><span></span></div><div class="hr-full-table">${list.map(c=>`<button class="hr-candidate-row" data-candidate="${c.id}"><span class="hr-candidate-id"><b>${c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</b><span><strong>${c.name}</strong><small>${c.location} · ${c.experience}</small></span></span><span>${c.role}<small>${c.salary}</small></span><span><em class="stage-${c.stage.toLowerCase()}">${stageLabel(c.stage)}</em></span><span><b>${c.score}%</b><small>${t.score}</small></span><i>→</i></button>`).join('')||`<div class="hr-empty-full">${t.empty}</div>`}</div>`;
    }
    function renderCandidateDetail(id){
      const c=candidateById(id);if(!c)return;state.selected=id;
      content.innerHTML=`<div class="hr-detail-page"><button class="hr-back-link" data-back>← ${t.candidates}</button><div class="hr-candidate-hero"><div class="hr-candidate-avatar">${c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><span class="stage-pill stage-${c.stage.toLowerCase()}">${stageLabel(c.stage)}</span><h1>${c.name}</h1><p>${c.role} · ${c.location}</p></div><div class="hr-hero-score"><small>${t.score}</small><b>${c.score}%</b></div></div><div class="hr-detail-tabs"><button class="active" data-ctab="overview">${t.overview}</button><button data-ctab="resume">${t.resume}</button><button data-ctab="skills">${t.softSkills}</button><button data-ctab="activity">${t.activity}</button></div><div data-candidate-panel>${candidateOverview(c)}</div></div>`;
      root.querySelector('[data-back]').onclick=()=>{state.selected=null;renderCandidates()};root.querySelectorAll('[data-ctab]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-ctab]').forEach(x=>x.classList.toggle('active',x===b));const p=root.querySelector('[data-candidate-panel]');p.innerHTML=b.dataset.ctab==='overview'?candidateOverview(c):b.dataset.ctab==='resume'?candidateResume(c):b.dataset.ctab==='skills'?candidateSkills(c):candidateActivity(c)});
    }
    function candidateOverview(c){return `<div class="hr-detail-layout"><div class="hr-panel"><div class="hr-panel-head"><div><b>${t.overview}</b><small>${en?'Candidate information':'Основна інформація'}</small></div></div><div class="hr-info-grid"><div><small>${t.email}</small><b>${c.email}</b></div><div><small>${t.phone}</small><b>${c.phone}</b></div><div><small>${t.experience}</small><b>${c.experience}</b></div><div><small>${t.salary}</small><b>${c.salary}</b></div></div></div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Actions':'Дії'}</b><small>${en?'Try the workflow':'Спробуйте сценарій'}</small></div></div><div class="hr-action-grid"><button data-caction="message">${t.message}<b>→</b></button><button data-caction="advance">${t.move}<b>→</b></button><button data-caction="interview">${t.schedule}<b>→</b></button><button data-caction="review">${t.review}<b>→</b></button></div></div><div class="hr-panel"><div class="hr-panel-head"><div><b>${t.notes}</b><small>${en?'Local editable note':'Локальна нотатка'}</small></div></div><textarea class="hr-note-box" placeholder="${en?'Write a note…':'Напишіть нотатку…'}"></textarea></div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Application history':'Історія заявки'}</b><small>${en?'Pipeline movement':'Рух по етапах'}</small></div></div><div class="hr-timeline">${stages.map((s,i)=>`<div class="${stages.indexOf(c.stage)>=i?'done':''}"><i></i><span>${stageLabel(s)}</span><small>${stages.indexOf(c.stage)>=i?(i===stages.indexOf(c.stage)?(en?'Current':'Поточний'):(en?'Done':'Готово')):''}</small></div>`).join('')}</div></div></div>`}
    function candidateResume(c){return `<div class="hr-detail-layout"><div class="hr-panel hr-resume-card"><div class="hr-panel-head"><div><b>${t.resume}</b><small>PDF · 1.8 MB</small></div><button class="hr-outline-btn" data-resume-download>${en?'Download':'Завантажити'} ↗</button></div><div class="hr-resume-preview"><div class="hr-doc-icon">PDF</div><div><b>${c.name} — Resume.pdf</b><small>${en?'Uploaded today':'Завантажено сьогодні'}</small></div></div></div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Summary':'Коротко'}</b><small>${c.role}</small></div></div><p class="hr-long-copy">${en?'Strong candidate with relevant experience, clear communication and a good fit for the current role.':'Сильний кандидат із релевантним досвідом, зрозумілою комунікацією та хорошою відповідністю поточній вакансії.'}</p></div></div>`}
    function candidateSkills(c){const labels=en?['Communication','Ownership','Teamwork','Problem solving','Adaptability']:['Комунікація','Відповідальність','Командна робота','Вирішення задач','Адаптивність'];return `<div class="hr-panel"><div class="hr-panel-head"><div><b>${t.skillsTitle}</b><small>${en?'1–10 scale':'Шкала 1–10'}</small></div><b class="hr-average">${(c.skills.reduce((a,b)=>a+b,0)/5).toFixed(1)}</b></div><div class="hr-skill-list">${labels.map((l,i)=>`<div><span>${l}</span><div><i style="width:${c.skills[i]*10}%"></i></div><b>${c.skills[i]}/10</b></div>`).join('')}</div></div>`}
    function candidateActivity(c){return `<div class="hr-panel"><div class="hr-panel-head"><div><b>${t.activity}</b><small>${en?'Latest events':'Останні події'}</small></div></div><div class="hr-activity-list">${c.activity.map((x,i)=>`<div><span>${i+1}</span><p>${x}<small>${i+1} day ago</small></p></div>`).join('')}</div></div>`}
    function renderVacancies(){content.innerHTML=`${header(t.vacancies,en?'Open positions and pipeline counts.':'Вакансії, статуси та кількість кандидатів.','addVacancy')}<div class="hr-card-grid">${data.vacancies.map(v=>`<button class="hr-vacancy-card" data-vacancy="${v.id}"><div><span class="status-dot status-${v.status.toLowerCase()}"></span><small>${statusLabel(v.status)}</small><em>${v.priority}</em></div><h3>${v.title}</h3><p>${v.company}</p><footer><span>${v.candidates} ${en?'candidates':'кандидатів'}</span><b>${v.salary}</b></footer></button>`).join('')}</div>`}
    function renderVacancyDetail(id){const v=data.vacancies.find(x=>x.id===id);content.innerHTML=`<div class="hr-detail-page"><button class="hr-back-link" data-back>← ${t.vacancies}</button><div class="hr-candidate-hero"><div class="hr-vacancy-icon">▦</div><div><span class="stage-pill stage-open">${statusLabel(v.status)}</span><h1>${v.title}</h1><p>${v.company} · ${v.salary}</p></div><div class="hr-hero-score"><small>${en?'Candidates':'Кандидати'}</small><b>${v.candidates}</b></div></div><div class="hr-detail-layout"><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Vacancy pipeline':'Воронка вакансії'}</b><small>${en?'Applications by stage':'Заявки за етапами'}</small></div></div>${['New','Screening','Interview','TestTask','Offer','Hired'].map((s,i)=>`<div class="hr-progress-row"><span>${stageLabel(s)}</span><div><i style="width:${[75,52,34,25,15,7][i]}%"></i></div><b>${[14,9,6,4,2,1][i]}</b></div>`).join('')}</div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Actions':'Дії'}</b></div></div><div class="hr-action-grid"><button data-vaction="pause">${v.status==='Paused'?(en?'Resume':'Відновити'):(en?'Pause':'Поставити на паузу')}<b>→</b></button><button data-go="candidates">${en?'View candidates':'Переглянути кандидатів'}<b>→</b></button></div></div></div></div>`;root.querySelector('[data-back]').onclick=renderVacancies;root.querySelector('[data-vaction]').onclick=()=>{v.status=v.status==='Paused'?'Open':'Paused';showToast(t.updated);renderVacancyDetail(id)}}
    function renderApplications(){const apps=data.candidates.filter(c=>c.stage!=='Rejected').map((c,i)=>({c,v:data.vacancies[i%data.vacancies.length]}));content.innerHTML=`${header(t.applications,en?'Candidate ↔ vacancy pipeline.')}<div class="hr-full-table"><div class="hr-table-head"><span>${t.candidates}</span><span>${t.vacancies}</span><span>${t.stage}</span><span>${t.score}</span><span></span></div>${apps.map(a=>`<button class="hr-candidate-row" data-candidate="${a.c.id}"><span class="hr-candidate-id"><b>${a.c.name.slice(0,2)}</b><span><strong>${a.c.name}</strong><small>${a.c.role}</small></span></span><span>${a.v.title}<small>${a.v.company}</small></span><span><em class="stage-${a.c.stage.toLowerCase()}">${stageLabel(a.c.stage)}</em></span><span><b>${a.c.score}%</b><small>${t.score}</small></span><i>→</i></button>`).join('')}</div>`}
    function renderInterviews(){content.innerHTML=`${header(t.interviews,en?'Schedule, track and review interviews.','addInterview')}<div class="hr-calendar-summary"><div><small>${t.today}</small><b>3</b><span>${en?'interviews':'співбесіди'}</span></div><div><small>${en?'Passed':'Пройдено'}</small><b>1</b><span>${en?'result':'результат'}</span></div><div><small>${en?'Avg. rating':'Сер. оцінка'}</small><b>9.3</b><span>/ 10</span></div></div><div class="hr-full-table"><div class="hr-table-head"><span>${t.date}</span><span>${t.name}</span><span>${t.type}</span><span>${t.result}</span><span></span></div>${data.interviews.map(i=>`<button class="hr-candidate-row" data-interview="${i.id}"><span><strong>${i.date}</strong><small>${i.owner}</small></span><span>${candidateName(i.candidateId)}<small>${candidateById(i.candidateId)?.role||''}</small></span><span>${i.type}</span><span><em class="result-${i.result.toLowerCase()}">${i.result==='Planned'?(en?'Planned':'Заплановано'):(en?'Passed':'Пройдено')}</em></span><i>→</i></button>`).join('')}</div>`}
    function renderInterviewDetail(id){const i=data.interviews.find(x=>x.id===id),c=candidateById(i.candidateId);content.innerHTML=`<div class="hr-detail-page"><button class="hr-back-link" data-back>← ${t.interviews}</button><div class="hr-candidate-hero"><div class="hr-vacancy-icon">◷</div><div><span class="stage-pill stage-open">${i.result==='Planned'?(en?'Planned':'Заплановано'):(en?'Passed':'Пройдено')}</span><h1>${candidateName(i.candidateId)}</h1><p>${i.type} · ${i.date}</p></div><div class="hr-hero-score"><small>${t.owner||'Owner'}</small><b>${i.owner}</b></div></div><div class="hr-detail-layout"><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Interview details':'Деталі співбесіди'}</b></div></div><div class="hr-info-grid"><div><small>${t.date}</small><b>${i.date}</b></div><div><small>${t.type}</small><b>${i.type}</b></div><div><small>${t.result}</small><b>${i.result}</b></div><div><small>${t.role}</small><b>${c.role}</b></div></div></div><div class="hr-panel"><div class="hr-panel-head"><div><b>${en?'Actions':'Дії'}</b></div></div><div class="hr-action-grid"><button data-ic="pass">${en?'Mark as passed':'Позначити як пройдено'}<b>→</b></button><button data-ic="review">${en?'Add review':'Додати відгук'}<b>→</b></button></div></div></div></div>`;root.querySelector('[data-back]').onclick=renderInterviews;root.querySelector('[data-ic=pass]').onclick=()=>{i.result='Passed';showToast(t.updated);renderInterviewDetail(id)};root.querySelector('[data-ic=review]').onclick=()=>openReviewModal(c)}
    function renderReviews(){content.innerHTML=`${header(t.reviews,en?'Interviewer feedback and ratings.')}<div class="hr-review-grid">${data.reviews.map(r=>{const c=candidateById(r.candidateId);return `<article class="hr-panel"><div class="hr-review-top"><div class="hr-candidate-id"><b>${c.name.slice(0,2)}</b><span><strong>${c.name}</strong><small>${c.role}</small></span></div><b class="hr-review-score">${r.rating}/10</b></div><div class="hr-stars">★★★★★</div><p>${r.comment}</p><small>${r.interviewer}</small></article>`}).join('')}</div>`}
    function renderSkills(){const labels=en?['Communication','Ownership','Teamwork','Problem solving','Adaptability']:['Комунікація','Відповідальність','Командна робота','Вирішення задач','Адаптивність'];content.innerHTML=`${header(t.skills,en?'Average soft-skill scores across current candidates.')}<div class="hr-panel"><div class="hr-skill-list big">${labels.map((l,i)=>{const avg=(data.candidates.reduce((s,c)=>s+c.skills[i],0)/data.candidates.length).toFixed(1);return `<div><span>${l}</span><div><i style="width:${avg*10}%"></i></div><b>${avg}</b></div>`}).join('')}</div></div>`}

    function bindPageActions(){
      root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter||'All';setPage(b.dataset.go)});
      root.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>renderCandidateDetail(Number(b.dataset.candidate)));
      root.querySelectorAll('[data-interview]').forEach(b=>b.onclick=()=>renderInterviewDetail(Number(b.dataset.interview)));
      root.querySelectorAll('[data-vacancy]').forEach(b=>b.onclick=()=>renderVacancyDetail(Number(b.dataset.vacancy)));
      root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.query='';renderCandidates();bindPageActions()});
      const cs=root.querySelector('[data-candidate-search');if(cs)cs.oninput=e=>{state.query=e.target.value;renderCandidates();bindPageActions()};
      const gs=root.querySelector('[data-global-search]');if(gs)gs.oninput=e=>{state.query=e.target.value;setPage('candidates')};
      root.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>showToast(en?'CSV export prepared':'CSV-експорт підготовлено'));
      root.querySelectorAll('[data-resume-download]').forEach(b=>b.onclick=()=>showToast(en?'Demo resume download':'Демонстрація завантаження резюме'));
      root.querySelectorAll('[data-caction=message]').forEach(b=>b.onclick=()=>showToast(t.messageCreated));
      root.querySelectorAll('[data-caction=advance]').forEach(b=>b.onclick=()=>{if(state.selected){const c=candidateById(state.selected),i=stages.indexOf(c.stage);c.stage=stages[Math.min(i+1,stages.length-1)];showToast(t.advance);renderCandidateDetail(c.id)}});
      root.querySelectorAll('[data-caction=interview]').forEach(b=>b.onclick=()=>openInterviewForm(state.selected));
      root.querySelectorAll('[data-caction=review]').forEach(b=>b.onclick=()=>openReviewModal(candidateById(state.selected)));
      root.querySelectorAll('[data-ic]').forEach(()=>{});
      root.querySelectorAll('[data-action]').forEach(b=>{b.onclick=()=>{const a=b.dataset.action;if(a==='addCandidate')openCandidateForm();if(a==='addVacancy')openVacancyForm();if(a==='addInterview')openInterviewForm()}});
      root.querySelectorAll('[data-top-add]').forEach(b=>b.onclick=()=>openCandidateForm());
      root.querySelectorAll('[data-interview]').forEach(b=>b.onclick=()=>renderInterviewDetail(Number(b.dataset.interview)));
    }

    function openCandidateForm(){openMiniModal(`<div class="hr-modal-head"><div><span>HR RESERVE</span><h2>${t.newCandidate}</h2><p>${t.demo}</p></div><button data-modal-close>×</button></div><form class="hr-form" data-form="candidate"><label>${t.name}<input name="name" required placeholder="${en?'Jane Doe':'Ім’я Прізвище'}"></label><label>${t.role}<input name="role" required placeholder="${en?'Backend Developer':'Backend Developer'}"></label><div class="hr-form-two"><label>${t.location}<input name="location" placeholder="Київ"></label><label>${t.email}<input name="email" placeholder="name@example.com"></label></div><div class="hr-form-two"><label>${t.experience}<input name="experience" placeholder="3 роки"></label><label>${t.salary}<input name="salary" placeholder="$1,700"></label></div><div class="hr-form-actions"><button type="button" data-modal-close class="hr-outline-btn">${t.cancel}</button><button class="hr-primary-btn" type="submit">${t.save}</button></div></form>`,()=>{modalCard.querySelector('[data-form=candidate]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const id=Math.max(...data.candidates.map(c=>c.id))+1;data.candidates.unshift({id,name:f.get('name'),role:f.get('role'),stage:'New',score:80,location:f.get('location')||'—',email:f.get('email')||'—',phone:'—',experience:f.get('experience')||'—',salary:f.get('salary')||'—',skills:[8,8,8,8,8],activity:[en?'Candidate created':'Кандидата створено']});closeModal();showToast(t.candidateAdded);setPage('candidates')}}})}
    function openVacancyForm(){openMiniModal(`<div class="hr-modal-head"><div><span>HR RESERVE</span><h2>${t.newVacancy}</h2><p>${t.demo}</p></div><button data-modal-close>×</button></div><form class="hr-form" data-form="vacancy"><label>${t.role}<input name="title" required placeholder="Frontend Developer"></label><div class="hr-form-two"><label>${t.company}<input name="company" placeholder="Acme Studio"></label><label>${t.salary}<input name="salary" placeholder="$1,500–2,100"></label></div><label>${t.status}<select name="status"><option value="Open">${t.open}</option><option value="Paused">${t.paused}</option></select></label><div class="hr-form-actions"><button type="button" data-modal-close class="hr-outline-btn">${t.cancel}</button><button class="hr-primary-btn" type="submit">${t.save}</button></div></form>`,()=>{modalCard.querySelector('[data-form=vacancy]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const id=Math.max(...data.vacancies.map(v=>v.id))+1;data.vacancies.push({id,title:f.get('title'),company:f.get('company')||'—',status:f.get('status'),priority:'Normal',candidates:0,salary:f.get('salary')||'—'});closeModal();showToast(t.vacancyAdded);setPage('vacancies')}})}
    function openInterviewForm(candidateId){openMiniModal(`<div class="hr-modal-head"><div><span>HR RESERVE</span><h2>${t.newInterview}</h2><p>${t.demo}</p></div><button data-modal-close>×</button></div><form class="hr-form" data-form="interview"><label>${t.name}<select name="candidate">${data.candidates.map(c=>`<option value="${c.id}" ${candidateId===c.id?'selected':''}>${c.name}</option>`).join('')}</select></label><div class="hr-form-two"><label>${t.date}<input type="datetime-local" name="date" required></label><label>${t.type}<select name="type"><option>Screening</option><option>Technical</option><option>Video</option><option>Final</option></select></label></div><label>${t.notes}<textarea name="notes" placeholder="${en?'Optional note…':'Додаткова нотатка…'}"></textarea></label><div class="hr-form-actions"><button type="button" data-modal-close class="hr-outline-btn">${t.cancel}</button><button class="hr-primary-btn" type="submit">${t.schedule}</button></div></form>`,()=>{modalCard.querySelector('[data-form=interview]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const d=new Date(f.get('date'));const id=Math.max(...data.interviews.map(i=>i.id))+1;data.interviews.push({id,date:d.toLocaleString('uk-UA').slice(0,16),candidateId:Number(f.get('candidate')),type:f.get('type'),result:'Planned',owner:'Recruiter'});closeModal();showToast(t.interviewAdded);setPage('interviews')}})}
    function openReviewModal(c){openMiniModal(`<div class="hr-modal-head"><div><span>HR RESERVE</span><h2>${t.review}</h2><p>${c.name} · ${c.role}</p></div><button data-modal-close>×</button></div><form class="hr-form" data-form="review"><label>${t.rating}<input name="rating" type="number" min="1" max="10" value="9" required></label><label>${t.comment}<textarea name="comment" required placeholder="${en?'Interview feedback…':'Відгук після співбесіди…'}"></textarea></label><div class="hr-form-actions"><button type="button" data-modal-close class="hr-outline-btn">${t.cancel}</button><button class="hr-primary-btn" type="submit">${t.save}</button></div></form>`,()=>{modalCard.querySelector('[data-form=review]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.reviews.unshift({candidateId:c.id,interviewer:'Max',rating:Number(f.get('rating')),comment:f.get('comment')});closeModal();showToast(t.saved);setPage('reviews')}})}

    root.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));
    root.querySelector('.hr-mobile-menu').onclick=()=>root.querySelector('.hr-sidebar').classList.toggle('open');
    renderPage();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initHRDemo);else initHRDemo();
})();